version: '3.1'
services:
  webkoperasi:
    image: odoo:16.0
    depends_on:
      - centraldb
    ports:
      - "8075:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=centraldb
    - USER=odoo
    - PASSWORD=myodoo
    networks:
      - central
  
  centraldb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    networks:
      - central
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - central

networks:
  central:
